name: workflow tests

on:
  push:
    branches:
      main
  pull_request:
    branches:
      main
      
jobs:
  test:
    name: do the test
    runs-on: ubuntu-latest
    
    steps:
      - name: check what takes so much space on rootfs
        run: |
          sudo find / 2>/dev/null | sudo xargs du -sh | sort -h
